qiniu/java-sdk

src/main/java/com/qiniu/storage/RecordKeyGenerator.java, src/main/java/com/qiniu/storage/Recorder.java, src/main/java/com/qiniu/storage/ResumeUploader.java, src/main/java/com/qiniu/storage/UploadManager.java, src/main/java/com/qiniu/storage/persistent/FileRecorder.java, src/test/java/com/qiniu/storage/RecordUploadTest.java, src/test/java/com/qiniu/storage/ResumeUploadTest.java
=> Resume recoder

src/main/java/com/qiniu/util/Auth.java
=> addDeleteAfterDays

build.gradle
=> fix bug: com.qiniu.http.Client throw NullPointerException

src/main/java/com/qiniu/common/AutoZone.java, src/main/java/com/qiniu/common/QiniuException.java, src/main/java/com/qiniu/common/Zone.java, src/main/java/com/qiniu/common/ZoneReqInfo.java, src/main/java/com/qiniu/http/Response.java, src/main/java/com/qiniu/processing/OperationManager.java, src/main/java/com/qiniu/storage/BucketManager.java, src/main/java/com/qiniu/storage/Configuration.java, src/main/java/com/qiniu/storage/FormUploader.java, src/main/java/com/qiniu/storage/ResumeUploader.java, src/main/java/com/qiniu/storage/StreamUploader.java, src/test/java/com/qiniu/common/AutoZoneTest.java, src/test/java/com/qiniu/storage/BucketTest.java, src/test/java/com/qiniu/storage/RecordUploadTest.java, src/test/java/com/qiniu/streaming/StreamingTest.java
rsf.qiniu.com 这个域名解析还没有准备好，暂时不测试、不合并。
可先看看 zone 、https 处理方式是否可以。
https://cf.qiniu.io/pages/viewpage.action?pageId=16092953
=> Https and zone

examples/DomainListDemo.java, src/main/java/com/qiniu/storage/BucketManager.java, src/test/java/com/qiniu/storage/BucketTest.java
https://developer.qiniu.com/kodo/api/1612/bucket-domainlist
=> Add DomainLists

examples/CdnRefreshDirsDemo.java, examples/CdnRefreshUrlsDemo.java
=> cdn refresh demo

build.gradle
okhttp 3.3.1 ==> 3.9.1
gson 2.6.2 ==> 2.8.2
=>  updates deps

src/main/java/com/qiniu/cdn/CdnManager.java, src/main/java/com/qiniu/processing/OperationManager.java, src/main/java/com/qiniu/rtc/RtcAppManager.java, src/main/java/com/qiniu/rtc/RtcRoomManager.java, src/main/java/com/qiniu/storage/BucketManager.java, src/main/java/com/qiniu/storage/UploadManager.java, src/main/java/com/qiniu/streaming/StreamingManager.java
1. 添加 bucketmanager 类中 删除bucket
2 添加bucketmanager 异步抓取接口
3 相关管理类添加构造函数，支持传入自定义的Client  #346
=> add delete bucket, async fetch  and  add client constructor

src/main/java/com/qiniu/common/Region.java, src/main/java/com/qiniu/common/Zone.java, src/main/java/com/qiniu/storage/Configuration.java
补充修改 https://github.com/qiniu/java-sdk/pull/394
1. uc.qbox.me 不改为 api.qiniu.com，因为有接口会404，比如 /v2/bucketInfo
2. 修复BUG。调用 Zone.zoneNa0()是，报com.qiniu.common.Region cannot be cast to com.qiniu.common.Zone
=> pull 394 补充修改

build.gradle, src/main/java/com/qiniu/common/Region.java, src/main/java/com/qiniu/storage/UploadManager.java, src/test/java/test/com/qiniu/TestConfig.java, src/test/java/test/com/qiniu/rtc/RtcTest.java, src/test/java/test/com/qiniu/storage/FormUploadTest2.java, src/test/java/test/com/qiniu/streaming/StreamingTest.java
1. 表单上传增加方法 putWithForm(InputStream inputStream, String key, String token, StringMap params, String mime, boolean checkCrc)，支持带inputStream上传
2. 增加1对应测试类FormUploadTest2
3. 修改类StreamingTest，使测试通过
4. 修复已知问题
=> FormUpload With InputStream

src/main/java/com/qiniu/linking/LinkingDeviceManager.java, src/main/java/com/qiniu/linking/model/Channel.java, src/main/java/com/qiniu/linking/model/Device.java
https://jira.qiniu.io/browse/LINK-623
=> LINK-623 linking java sdk增加网关设备支持

src/main/java/com/qiniu/http/Client.java
=> 添加了 SetAppName() 方法

examples/UploadBySelfDefiningDomain.java
new upload func by  self defining domain,add a new file into example
=> add new upload func by  self defining domain

src/main/java/com/qiniu/processing/OperationManager.java, src/test/java/test/com/qiniu/processing/PfopTest.java, src/test/java/test/com/qiniu/storage/FormUploadTest.java
https://jira.qiniu.io/browse/TS-1035
=> check prefop id by GET

src/main/java/com/qiniu/qvs/PTZManager.java, src/test/java/test/com/qiniu/qvs/PTZTest.java
=> LINK-1702  PTZ qvs-java-sdk

src/main/java/com/qiniu/qvs/DeviceManager.java, src/main/java/com/qiniu/qvs/QvsMap.java, src/main/java/com/qiniu/qvs/model/PlayContral.java, src/main/java/com/qiniu/qvs/model/VoiceChat.java, src/test/java/test/com/qiniu/qvs/DeviceManagerTest.java
=> qvs LINK-2695 add controlGBRecord

README.md, src/main/java/com/qiniu/common/Zone.java, src/main/java/com/qiniu/storage/BucketManager.java, src/main/java/com/qiniu/storage/Region.java, src/test/java/test/com/qiniu/TestConfig.java, src/test/java/test/com/qiniu/storage/BucketTest.java
https://jira.qiniu.io/browse/KODO-15344
=> add region:ap-northeast-1

src/main/java/com/qiniu/rtc/model/AppParam.java, src/main/java/com/qiniu/rtc/service/AppService.java, src/test/java/test/com/qiniu/rtc/RtcTest.java
https://jira.qiniu.io/browse/QRTC-1984
=> QRTC-1984  rtc v3 update app bug fix

CHANGELOG.md, README.md, src/main/java/com/qiniu/common/Constants.java, src/main/java/com/qiniu/http/Response.java, src/main/java/com/qiniu/storage/BaseUploader.java, src/main/java/com/qiniu/storage/FormUploader.java, src/main/java/com/qiniu/storage/ResumeUploadPerformerV1.java, src/main/java/com/qiniu/storage/ResumeUploadSource.java, src/main/java/com/qiniu/storage/ResumeUploadSourceFile.java, src/main/java/com/qiniu/storage/ResumeUploader.java, src/main/java/com/qiniu/storage/Retry.java
https://jira.qiniu.io/browse/KODO-15775
=> Resume check ctx expire

src/main/java/com/qiniu/storage/BucketManager.java
=> deprecated listV2

src/main/java/com/qiniu/storage/BucketManager.java
=> Change Api host

src/main/java/com/qiniu/qvs/StreamManager.java, src/main/java/com/qiniu/qvs/model/DynamicLiveRoute.java, src/main/java/com/qiniu/qvs/model/StaticLiveRoute.java
1，qvs静态模式添加playExpireSec字段；
2，qvs动态模式添加playExpireSec字段。
=> LINK-2757 qvs add playExpireSec

src/main/java/com/qiniu/storage/Region.java
=> remove region: ap-northeast-1

src/main/java/com/qiniu/storage/model/FileInfo.java, src/main/java/com/qiniu/storage/model/StorageType.java, src/test/java/test/com/qiniu/storage/BucketTest2.java
=> support intelligent tiering
